### ISSUE TITLE
Where to set FFMpeg path?

### ISSUE THREAD

**Issue by DaGooseYT** [AydinAdn/MediaToolkit#117]
Thank you for creating this tool, it is very helpful! This may seem like a stupid question, but how do I set/change the file path for FFMpeg so that MediaToolKit can work? I keep getting exception “FFMpeg GZip stream is null” on line 106 in `EngineBase.cs` File. Any help is appreciated, thanks.

**Comment by paniclp** [comment]
As far as I know,this tool has need not set ffmpeg file path, you can directly use this tool to convert video
