### ISSUE TITLE
Is there a way to get thumbnail of swf?

### ISSUE THREAD

**Issue by srpeirce** [AydinAdn/MediaToolkit#20]
Hello,
I notice swf is not in your supported formats - but it is supported by ffmpeg.

I wonder if there is a way to use this to get a thumbnail from swf?

Thanks for your help

**Comment by AydinAdn** [comment]
SWF files can include vector graphics and ActionScript, which will most likely raise issues when you attempt such a task, although you shouldn't have any issues using FLV.
