### ISSUE TITLE
[Feature request] Watermarking videos using an image 

### ISSUE THREAD

**Issue by gonzell** [AydinAdn/MediaToolkit#23]
A big improvement, you could add the option to insert a watermark in the videos, from an image. It would be a great help this functionality.

**Comment by AydinAdn** [comment]
I've looked into this more recently and I have a feeling it's going to open a whole can of worms...

For instance, the arguments used to images differ from the arguments used during adding text, then you have to be able to configure the location of the content, the size of the content, if using text the font and weight and etc... the transparency, timings of displaying, etc etc just leaves too much to cover. I might add a basic implementation later one day but if anyone else wants to have a stab at it, I'll be happy to merge them in
