### ISSUE TITLE
MediaToolKit folder containing ffmpeg, not on application folder

### ISSUE THREAD

**Issue by dust63** [AydinAdn/MediaToolkit#24]
Hi, just one question. why the folder MediaToolkit was not leave on Application StartUp path. 
This is my sample code:

```vb
Dim engine As MediaToolkit.Engine
engine = New MediaToolkit.Engine
 Dim file As New MediaToolkit.Model.MediaFile
 file.Filename = "D:\Utils\big_buck_bunny_1080p_surround.mov"
 engine.GetMetadata(file)
```
When i'm use it a folder MediaToolkit was created on my D: drive within it, ffmpeg.

Thanks for your work.

Regards.
Romain.

**Comment by AydinAdn** [comment]
The change was made as some users of the library did not have access to the `Temp` folder where the library used to be placed in. However you can change the behaviour if you wish to do so by entering the `FilePath` of the `FFmpeg.exe` library in the constructor of the `Engine` class.

Does that resolve your issue?

**Comment by dust63** [comment]
Thanks, I've tested and it's ok. Issue resolved. Sorry for the convenient.

Do you think that you can list DShow device and options like this article ?
https://trac.ffmpeg.org/wiki/DirectShow

The idea is to use your library to make live capture.

Regards.

**Comment by TarasKovalyk** [comment]
I have an issue with this lib. I use it with ASP.NET app. But it doesn't generate of the thumbnail when i pass url to file besides it doesn't work even when I  pass input file as string path.

**Comment by nemtajo** [comment]
Hm.. Would it be sensible to extract ffmpeg.exe in the .net project output folder (Debug/bin, Release/bin)? That would simplify deployment of applications to the cloud.
Now we have to create an msbuild step to copy the executable to project output folder.
I know the Engine constructor accepts the ffmpegPath argument, but it feels a bit hacky.
What is your opinion on it?

**Comment by bobmagrega** [comment]
Hey everyone! I am not in C programming at all, just really need to do a thing with it. Can you guys advise me on how to change the path where ffmpeg.exe is deployed? By default it drops in C drive under mediatoolkit folder and I'd like it to be on the same folder as the project.

I found that there's a variable EngineBase.FFmpegFilePath inside EngineBase class but it's readonly.
