### ISSUE TITLE
The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by pouriyaGhasemi** [AydinAdn/MediaToolkit#34]
hi i use iis express and VS 2012 asp mvc
help me.
why at engine.GetMetadata(inputFile) exception error "The specified executable is not a valid application for this OS platform"?
my code
```
var inputFile = new MediaToolkit.Model.MediaFile { Filename = path };

            using (var engine = new MediaToolkit.Engine())
            {
                engine.GetMetadata(inputFile);
            }
            return inputFile;
```

**Comment by AydinAdn** [comment]
Hey @pouriyaGhasemi, what environment are you running the app in? Also, are you able to run that code within a console app in the same environment?

I highly recommend that you **don't** use FFmpeg directly from a web application. Use MSMQ to queue whatever that needs to be processed by FFmpeg and have another dedicated service or even a console app dequeuing the work items from MSMQ and processing them separately. 

Doing it in the way that you are, you're going to run into one issue after another.
