### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by idoyana** [AydinAdn/MediaToolkit#4]
Hi,

I started to use your library in and it looks great
only one question,
on production the engine create the file "ffmpeg.exe" in "'C:\Windows\TEMP\MediaToolkit", and from security reasons that could be a problem
is there a way to define a specific directory for this file ?

I also tried to copy "ffmpeg.exe" to bin directory, but it didn't work

**Comment by AdamZC** [comment]
Hi, I got the exact issue as above, any resolution?

**Comment by AydinAdn** [comment]
To anyone who might have similar issues, you can specify the file path of your own copy of FFmpeg.

This will help prevent it from attempting to extract its own copy. When creating a nice instance of Engine, just add the path of `FFmpeg.exe` to the constructor.
