### ISSUE TITLE
HD video splitting is very slow

### ISSUE THREAD

**Issue by sandeepd1** [AydinAdn/MediaToolkit#45]
Splitting process become very slow if there is a HD video file having size around 2 GB.
Convert method takes approx 30 seconds or more for one split of Timespan 15 sec.

**Comment by AydinAdn** [comment]
Media conversions take time, even more so when in HD. It's a resource intensive process which you can somewhat get around by upgrading your hardware or attempting to optimize the commands to your own specific use case.
