### ISSUE TITLE
Access to the path '\MediaToolkit' is denied.

### ISSUE THREAD

**Issue by waiyanpaing** [AydinAdn/MediaToolkit#54]
I used this libery file on my MVC Web application and uploaded on Dodaddy.
"Access to the path '\MediaToolkit' is denied." error occour and can't finish converting process.
The converting process is very work when I used at local.
So, somebody help how to fix this error. Thanks all.

**Comment by dishyshyguy** [comment]
Add the ffmpeg.exe on a virtual folder in your website and use the app settings  mediatoolkit.ffmpeg.path to point to that file.  Alternatively you can use pass the location on the engine constructor e.g. using (var engine= new engine (server.mappath ("~/content/ffmpeg.exe)))

**Comment by nnemesispt** [comment]
Using the constructor with the file path solved it right. Thanks :)
