### ISSUE TITLE
MP4 to MP3 Converting

### ISSUE THREAD

**Issue by EgoistDeveloper** [AydinAdn/MediaToolkit#59]
Can I convert mp3 to mp4? If possible, would you disclose it with a small sample?

**Comment by AydinAdn** [comment]
var inputFile = new MediaFile {Filename = @"C:\Path\To_Video.mp4"};
var outputFile = new MediaFile {Filename = @"C:\Path\To_Save_Audio.mp3"};

```
using (var engine = new Engine())
{
    engine.Convert(inputFile, outputFile);
}
```
