### ISSUE TITLE
Is it possible to run this on shared web hosting

### ISSUE THREAD

**Issue by rexn8r** [AydinAdn/MediaToolkit#60]
hello

i have integrated the toolkit in my asp .net website. but when i run it on a shared hosting server, it gives me an error.

is it possible to convert files on shared hosting?

thanks
raxit

**Comment by HassanHashemi** [comment]
It depends on your hosting provider policy, though almost all sharing provider do not allow apps to run arbitrary exe (so there is high chance that you cant run this on a shared hosting).

**Comment by AydinAdn** [comment]
You wouldn't be able to (or at least you shouldn't be able to due to the risks arising from being able to run an executable, in addition to the stress that this would impose on the shared cpus)
