### ISSUE TITLE
FileName with spaces

### ISSUE THREAD

**Issue by JohnDLe** [AydinAdn/MediaToolkit#91]
Doesn't work in C# when the filename has a space in it. For example:  

var file = @"C:\Temp\My File.mp4"

engine.GetMetaData(mediaFile) throws a System.IO.FileNotFoundException: 'Input file not found'

I tried adding a single and double quotation around the file string and it still doesn't work.

**Comment by it14118** [comment]
Greetings, Could you provide more information? Maybe a code snippet or something? Thanks

**Comment by JohnDLe** [comment]
This is a non issue, the problem was with something else. Thanks for replying.

**Comment by Heesel** [comment]
> This is a non issue, the problem was with something else. Thanks for replying.

What was the issue then?. I am facing the same issue. How did you solve it?

**Comment by JohnDLe** [comment]
> > This is a non issue, the problem was with something else. Thanks for replying.
> 
> What was the issue then?. I am facing the same issue. How did you solve it?

I solved it by removing all spaces in the directory and file name.
